#!/usr/bin/env tsx
// ─── @trembus/animation-catalog: Codegen — Sync From Sources ────────────────
//
// Reads:
//   - __master-asset-ids-validated.csv (kind=Animation rows)  → assetId, tglName
//   - __animation-triage-ledger.csv (Track A output)          → lengthSec, looped, compatibleRigs, status
//   - src/catalog.overrides.ts (hand-curated)                  → logicalName, sub, domain, priority, tags, notes
//
// Emits:
//   - src/catalog.ts (the typed `Animations` nested record)
//
// Workflow: upload anim → rename on Creator Hub → run validate_asset_ids.py →
// run `pnpm sync` → review diff → fill in overrides for new entries → commit.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
// PKG_ROOT = .../Master-Managed/Repositories/Gaming/Roblox-Repositories/roblox-packages-mono/packages/animation-catalog
// Need to go up 6 levels to reach Master-Managed/, then descend into Project-Spaces/...
const ASSETS_ROOT = resolve(PKG_ROOT, "../../../../../../Project-Spaces/Roblox-Development/Soul-Steel-Official/external-locations/assets");
const MASTER_CSV = resolve(ASSETS_ROOT, "__master-asset-ids-validated.csv");
const LEDGER_CSV = resolve(ASSETS_ROOT, "__animation-triage-ledger.csv");
const OVERRIDES_TS = resolve(PKG_ROOT, "src/catalog.overrides.ts");
const CATALOG_OUT = resolve(PKG_ROOT, "src/catalog.ts");

type CsvRow = Record<string, string>;

function parseCsv(path: string): CsvRow[] {
  if (!existsSync(path)) return [];
  const text = readFileSync(path, "utf8").trim();
  const [header, ...rows] = text.split("\n");
  const cols = header.split(",").map((s) => s.trim());
  return rows.map((line) => {
    const vals = line.split(",");
    const row: CsvRow = {};
    cols.forEach((c, i) => (row[c] = (vals[i] ?? "").trim()));
    return row;
  });
}

interface MergedEntry {
  assetId: string;
  tglName: string;
  logicalName?: string;
  sub?: string;
  domain?: string;
  compatibleRigs?: string[];
  lengthSec?: number;
  priority?: string;
  looped?: boolean;
  status?: string;
  tags?: string[];
  notes?: string;
}

function loadOverrides(): Record<string, Partial<MergedEntry>> {
  if (!existsSync(OVERRIDES_TS)) return {};
  const text = readFileSync(OVERRIDES_TS, "utf8");
  // Naive extraction: find `export const overrides: ... = { ... };`
  // For robustness in real use we'd transpile and import; this is a quick parser.
  const match = text.match(/export\s+const\s+overrides[^=]*=\s*({[\s\S]*?});\s*\n/);
  if (!match) return {};
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  try {
    return new Function(`return ${match[1]}`)() as Record<string, Partial<MergedEntry>>;
  } catch {
    return {};
  }
}

function emitCatalog(entries: MergedEntry[]): string {
  const root: Record<string, unknown> = {
    combat: { melee: {} },
    cast: {},
    movement: {},
    emote: {},
    npc: {},
    ability: { blood: {}, decay: {}, spirit: {}, robotic: {}, fateless: {}, shared: {} },
    transformation: {},
    beam: {},
    ki: {},
    _scratch: {},
  };

  for (const e of entries) {
    if (!e.logicalName) continue;
    const path = e.logicalName.split(".");
    let cursor = root;
    for (let i = 0; i < path.length - 1; i++) {
      cursor[path[i]] = cursor[path[i]] ?? {};
      cursor = cursor[path[i]] as Record<string, unknown>;
    }
    cursor[path[path.length - 1]] = {
      logicalName: e.logicalName,
      assetId: `rbxassetid://${e.assetId}`,
      tglName: e.tglName,
      cat: "ANI" as const,
      sub: e.sub ?? "CST",
      domain: e.domain ?? "shared",
      compatibleRigs: e.compatibleRigs ?? ["R15"],
      lengthSec: e.lengthSec ?? 0,
      priority: e.priority ?? "Core",
      looped: e.looped ?? false,
      status: e.status ?? "PLACEHOLDER",
      ...(e.tags ? { tags: e.tags } : {}),
      ...(e.notes ? { notes: e.notes } : {}),
    };
  }

  const body = JSON.stringify(root, null, 2)
    .replace(/"([A-Za-z_][A-Za-z0-9_]*)":/g, "$1:")
    .replace(/"ANI"/g, '"ANI" as const');

  return `// ─── @trembus/animation-catalog: Generated Catalog Tree ─────────────────────
//
// THIS FILE IS GENERATED by \`scripts/sync-from-sources.ts\`. Do not hand-edit.
// Edit \`src/catalog.overrides.ts\` for hand-curated metadata.
// Generated: ${new Date().toISOString()}

import type { AnimationCatalogEntry } from "./types";

export const Animations = ${body} as const;
`;
}

// ─── main ────────────────────────────────────────────────────────────────────
const csvRows = parseCsv(MASTER_CSV).filter((r) => r.kind === "Animation" || r.actual_kind === "Animation");
const ledger = new Map(parseCsv(LEDGER_CSV).map((r) => [r.assetId, r]));
const overrides = loadOverrides();

const entries: MergedEntry[] = csvRows
  .filter((row) => !overrides[row.id]?.notes?.includes("__ignore"))
  .map((row): MergedEntry => {
    const id = row.id;
    const ov = overrides[id] ?? {};
    const led = ledger.get(id);

    return {
      assetId: id,
      tglName: ov.tglName ?? row.tglName ?? `ANI_CST_Unnamed_${id.slice(-4)}_BLK`,
      logicalName: ov.logicalName,
      sub: ov.sub,
      domain: ov.domain,
      priority: ov.priority,
      tags: ov.tags,
      notes: ov.notes,
      lengthSec: led ? Number(led.length) : undefined,
      looped: led ? led.looped === "true" : undefined,
      compatibleRigs: led?.rigUsed ? [led.rigUsed as MergedEntry["compatibleRigs"] extends (infer T)[] ? T : never] : undefined,
      status:
        led?.visualVerdict === "works" ? "READY"
        : led?.visualVerdict === "broken" ? "BLOCKED"
        : led ? "PLACEHOLDER"
        : undefined,
    };
  })
  .filter((e) => e.logicalName);  // skip entries without a logical name (need human triage first)

writeFileSync(CATALOG_OUT, emitCatalog(entries));
console.log(`✓ Wrote ${entries.length} catalog entries to ${CATALOG_OUT}`);
console.log(`  CSV rows scanned: ${csvRows.length}`);
console.log(`  Ledger rows available: ${ledger.size}`);
console.log(`  Overrides defined: ${Object.keys(overrides).length}`);
const orphans = csvRows.filter((r) => !overrides[r.id]?.logicalName).length;
if (orphans > 0) {
  console.log(`  ⚠ ${orphans} CSV animation(s) lack logical names — add to catalog.overrides.ts`);
}
