// ─── @trembus/animation-catalog: Generated Catalog Tree ─────────────────────
//
// THIS FILE IS GENERATED by `scripts/sync-from-sources.ts`.
// Do not hand-edit entry data — edit `src/catalog.overrides.ts` instead.
//
// The codegen script reads:
//   - external-locations/assets/__master-asset-ids-validated.csv (kind=Animation)  → assetId, tglName
//   - external-locations/assets/__animation-triage-ledger.csv                       → lengthSec, looped, compatibleRigs, status
//   - src/catalog.overrides.ts                                                       → logicalName, sub, domain, priority, tags, notes
//
// Initial scaffold: empty tree. Populated post-Track-A (triage ledger generation).
// Steel City priority order: NPC → Combat → Movement → Transformation.

import type { AnimationCatalogEntry } from "./types";

/**
 * The typed catalog tree. Top-level branches are functional buckets; second-level
 * branches by domain only where it varies (`ability.<domain>.*`); the `domain`
 * field on each entry is the source of truth for filtering.
 *
 * Conventional tree shape (filled by codegen):
 *
 *   Animations.combat.melee.punchLeft        → ANI_CMB_PunchLeft_FNL
 *   Animations.cast.fastShot                 → ANI_CST_FastShot_FNL
 *   Animations.movement.shadowstep           → ANI_MOV_Shadowstep_FNL
 *   Animations.npc.chase                     → ANI_NPC_Chase_FNL
 *   Animations.ability.blood.basicSkill      → ANI_ABL_BloodBasic_BLK
 *   Animations.transformation.iron           → ANI_TRN_IronForm_BLK
 *   Animations.beam.devilBeam                → ANI_BEM_DevilBeam_BLK
 *   Animations.ki.kamehameha                 → ANI_KI_Kamehameha_BLK
 *   Animations._scratch.uglyPunch            → ANI_CMB_UglyPunch_BLK   (quarantined)
 *
 * Until the triage ledger lands, this is empty.
 */
export const Animations = {
  combat: { melee: {} as Readonly<Record<string, AnimationCatalogEntry>> },
  cast: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  movement: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  emote: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  npc: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  ability: {
    blood: {} as Readonly<Record<string, AnimationCatalogEntry>>,
    decay: {} as Readonly<Record<string, AnimationCatalogEntry>>,
    spirit: {} as Readonly<Record<string, AnimationCatalogEntry>>,
    robotic: {} as Readonly<Record<string, AnimationCatalogEntry>>,
    fateless: {} as Readonly<Record<string, AnimationCatalogEntry>>,
    shared: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  },
  transformation: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  beam: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  ki: {} as Readonly<Record<string, AnimationCatalogEntry>>,
  /** Quarantined scratch animations. CI lint forbids imports of `_scratch.*` from outside this package. */
  _scratch: {} as Readonly<Record<string, AnimationCatalogEntry>>,
} as const;
